USE [master]
GO

/****** Object:  Database [HouseholdsDb]    Script Date: 4/2/2021 12:21:32 AM ******/
CREATE DATABASE [HouseholdsDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HouseholdsDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\HouseholdsDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HouseholdsDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\HouseholdsDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HouseholdsDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HouseholdsDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HouseholdsDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HouseholdsDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HouseholdsDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HouseholdsDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [HouseholdsDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HouseholdsDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HouseholdsDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HouseholdsDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HouseholdsDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HouseholdsDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HouseholdsDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HouseholdsDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HouseholdsDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HouseholdsDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HouseholdsDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HouseholdsDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HouseholdsDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HouseholdsDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HouseholdsDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HouseholdsDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HouseholdsDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HouseholdsDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HouseholdsDb] SET  MULTI_USER 
GO

ALTER DATABASE [HouseholdsDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HouseholdsDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HouseholdsDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HouseholdsDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HouseholdsDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HouseholdsDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HouseholdsDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HouseholdsDb] SET  READ_WRITE 
GO


